version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: easystepconnect_v0
  MYSQL_PASSWORD: password

services:
  mysql_db:
    container_name: esc-mysql
    hostname: esc-mysql
    image: mysql:8.0
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "13306:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: esc-mysql

  server:
    container_name: esc-server
    hostname: esc-server
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: loalhost
      CLIENT_ADDRESS: "esc-client:3000"
    ports:
      - "3001:3001"

  client:
    container_name: esc-client
    hostname: esc-client
    build:
      dockerfile: Dockerfile
      context: ./client
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
      SERVER_ADDRESS: "esc-server:3001"
      NODE_OPTIONS: "--openssl-legacy-provider"
    ports:
      - "80:3000"

  adminer:
    container_name: esc-adminer
    hostname: esc-adminer
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8000:8080"
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
